### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Zibri** [mnismt/CompressedCrack#5]
Traceback (most recent call last):
  File "crack.py", line 139, in <module>
    main()
  File "crack.py", line 134, in main
    check = Check(sys.argv[1:])
  File "crack.py", line 32, in __init__
    if (self.CheckFileExist(Arg)):
  File "crack.py", line 39, in CheckFileExist
    if (os.path.isfile(Arg[1])):
IndexError: list index out of range

**Comment by guowanhui** [comment]
cmd

**Comment by mnismt** [comment]
Please check the new [README](https://github.com/mnismt/CompressedCrack?tab=readme-ov-file#usage) file to understand how to use this tool.
